language: node_js
node_js: stable

cache:
    directories:
    - node_modules


install: npm install

# 编译
script:
  - hexo clean
  - hexo generate

# 部署
after_script:
  - hexo deploy

# 部署
# deploy:
#   provider: pages
#   github-token: $GITHUB_TOKEN
#   local-dir: public
#   on:
#     branch: master
