language: node_js
node_js: stable

cache:
    directories:
    - node_modules


install: npm install

# 编译
script:
  - hexo clean
  - hexo generate

# 部署
after_script:
  - git config user.name "travis deploy"
  - git config user.email "iamdbd@163.com"
  - hexo deploy
