language: node_js
node_js: stable

cache:
    directories:
    - node_modules

install: npm install

# 编译
script: hexo g

# 部署
deploy: 
  provider: pages
  github-token: $GITHUB_TOKEN
  local-dir: public
  on:
    branch: master

