language: node_js
node_js: stable

install: npm install

after_install: rm package-lock.json

script: hexo g


deploy: 
  provider: pages
  github-token: $GITHUB_TOKEN
  local-dir: public
  on:
    branch: master