name: Deploy
on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: npm install, hexo generate
      uses: actions/setup-node@v1
    - run: npm install
    - run: hexo generate
    - name: deploy site to gh-pages branch
      uses: bookshiyi/action-hexo@master
      env:
        CI: true
