name: Deploy
on:
  push:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: '10.x'
    - name: npm install, hexo generate
      uses: actions/setup-node@v1
      run: npm install && hexo generate
    - name: GitHub Action for hexo
      uses: heowc/action-hexo@1.0.2
      env:
        CI: true
